### ISSUE TITLE
Error: Cannot find module './build/Debug/buffertools.node'

### ISSUE THREAD

**Issue by off-bank** [andrewfhart/openassets#6]
I'm trying to browserify it, but I get this error:

/usr/share/openassets# browserify index.js -o bundle.js
Error: Cannot find module './build/Debug/buffertools.node' from '/usr/share/openassets/node_modules/buffertools'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)

**Comment by grubino** [comment]
+1

**Comment by igorcandeia** [comment]
App threw an error during load
Error: Cannot find module './build/Debug/buffertools.node'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\Users\Igor\electron-quick-start\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Igor\electron-quick-start\node_modules\buffertools\buffertools.js:26:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
